### ISSUE TITLE
Coordenada z

### ISSUE THREAD

**Issue by dianagtf** [dianagtf/IWVG.SwC.Diana.Armijo#1]
Clase Point: Aumentar a una tercera coordenada llamada z

**Comment by dianagtf** [comment]
Hola @socrtx! He visto que no has terminado aún este ticket, crees que podrás revisarlo hoy? Si no te es posible, por favor, avísame antes de esta tarde para que pueda asignárselo a otro programador.
Muchas gracias!

**Comment by socrtx** [comment]
**Ya lo tienes, perdona pero no me da la vida, con tanta practica**

**Comment by dianagtf** [comment]
Hola @socrtx , he visto que travis me da error. Comprobándolo, parece que el test de la clase Point no es correcto. Por favor, revísalo de nuevo.

Puedes crear un nuevo issue llamado issue#01_test.

Gracias!

**Comment by socrtx** [comment]
Ya lo tienes!

**Comment by socrtx** [comment]
cierra tu el ticket si estuviera bien

**Comment by dianagtf** [comment]
Muchas gracias @socrtx. Parece estar todo bien!
