### ISSUE TITLE
Comparar fracciones: mayor que

### ISSUE THREAD

**Issue by dianagtf** [dianagtf/IWVG.SwC.Diana.Armijo#4]
Clase Fraction: Comparar si una fracción es mayor que otra

**Comment by dianagtf** [comment]
Hola @socrtx! He visto que no has terminado aún este ticket, crees que podrás revisarlo hoy? Si no te es posible, por favor, avísame antes de esta tarde para que pueda asignárselo a otro programador.
Muchas gracias!

**Comment by socrtx** [comment]
Estoy con el

**Comment by socrtx** [comment]
Revisarlo  y me cuentas

**Comment by dianagtf** [comment]
Hola @socrtx He visto que falta el test para el nuevo método
Por favor, inclúyelo y me avisas.
Gracias!

**Comment by socrtx** [comment]
issue#04  Create FractionTest:testGreaterThan is done

**Comment by dianagtf** [comment]
Perfecto @socrtx!! Cierro este ticket
Muchas gracias!
